# Generated by Django 4.2.6 on 2023-10-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_docket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='docket',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
